federation_version: =2.6.0
subgraphs:
  soundtracks:
    routing_url: http://localhost:8080/graphql
    schema:
      file: ./src/main/resources/schema/schema.graphqls # Schema provided via file
  recipes: # Schema downloaded from GraphOS registry
    schema:
      graphref: Music-Matcher-ywhwhq@current
      subgraph: recipes